<?php

namespace Database\Seeders;

use App\Models\Locations;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocalidadesBuenosAiresSeeder extends Seeder{

public function run(): void{
    $this->CreateLocalidadesBuenosAires();
}

private function CreateLocalidadesBuenosAires(){

    $data = [
        [ 'name'=>'Villa Lynch Pueyrredón','state_id'=>1818 ],
        [ 'name'=>'Bellocq','state_id'=>1818 ],
        [ 'name'=>'Hortensia','state_id'=>1818 ],
        [ 'name'=>'Coronel Pringles','state_id'=>1818 ],
        [ 'name'=>'El Divisorio','state_id'=>1818 ],
        [ 'name'=>'Cascada','state_id'=>1818 ],
        [ 'name'=>'Curamalal','state_id'=>1818 ],
        [ 'name'=>"D'Orbigny",'state_id'=>1818 ],
        [ 'name'=>'Pasman','state_id'=>1818 ],
        [ 'name'=>'Santa María','state_id'=>1818 ],
        [ 'name'=>'Andant','state_id'=>1818 ],
        [ 'name'=>'Arboledas','state_id'=>1818 ],
        [ 'name'=>'La Larga','state_id'=>1818 ],
        [ 'name'=>'Salazar','state_id'=>1818 ],
        [ 'name'=>'General Alvear','state_id'=>1818 ],
        [ 'name'=>'Casbas','state_id'=>1818 ],
        [ 'name'=>'General La Madrid','state_id'=>1818 ],
        [ 'name'=>'Garré','state_id'=>1818 ],
        [ 'name'=>'Laguna Alsina','state_id'=>1818 ],
        [ 'name'=>'Henderson','state_id'=>1818 ],
        [ 'name'=>'Herrera Vegas','state_id'=>1818 ],
        [ 'name'=>'Recalde','state_id'=>1818 ],
        [ 'name'=>'Colonia San Miguel','state_id'=>1818 ],
        [ 'name'=>'Hinojo','state_id'=>1818 ],
        [ 'name'=>'Sierras Bayas','state_id'=>1818 ],
        [ 'name'=>'Villa Alfredo Fortabat','state_id'=>1818 ],
        [ 'name'=>'Capitán Castro','state_id'=>1818 ],
        [ 'name'=>'Francisco Madero','state_id'=>1818 ],
        [ 'name'=>'Juan José Paso','state_id'=>1818 ],
        [ 'name'=>'Nueva Plata','state_id'=>1818 ],
        [ 'name'=>'Pehuajó','state_id'=>1818 ],
        [ 'name'=>'17 de Agosto','state_id'=>1818 ],
        [ 'name'=>'Villa Castelar','state_id'=>1818 ],
        [ 'name'=>'Arroyo Corto','state_id'=>1818 ],
        [ 'name'=>'Goyena','state_id'=>1818 ],
        [ 'name'=>'Las Encadenadas','state_id'=>1818 ],
        [ 'name'=>'Pigüé','state_id'=>1818 ],
        [ 'name'=>'Crotto','state_id'=>1818 ],
        [ 'name'=>'Tapalqué','state_id'=>1818 ],
        [ 'name'=>'Sierra de la Ventana','state_id'=>1818 ],
        [ 'name'=>'Tres Picos','state_id'=>1818 ],
        [ 'name'=>'La Gruta','state_id'=>1818 ],
        [ 'name'=>'Berutti','state_id'=>1818 ],
        [ 'name'=>'Girodias','state_id'=>1818 ],
        [ 'name'=>'La Carreta','state_id'=>1818 ],
        [ 'name'=>'30 de Agosto','state_id'=>1818 ],
        [ 'name'=>'San Mayol','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Thompson','state_id'=>1818 ],
        [ 'name'=>'Barrio El Taladro','state_id'=>1818 ],
        [ 'name'=>'Cañuelas','state_id'=>1818 ],
        [ 'name'=>'Santa Rosa','state_id'=>1818 ],
        [ 'name'=>'Uribelarrea','state_id'=>1818 ],
        [ 'name'=>'Gorchs','state_id'=>1818 ],
        [ 'name'=>'General Las Heras','state_id'=>1818 ],
        [ 'name'=>'Villars','state_id'=>1818 ],
        [ 'name'=>'Lobos','state_id'=>1818 ],
        [ 'name'=>'Salvador María','state_id'=>1818 ],
        [ 'name'=>'Barrio Santa Rosa','state_id'=>1818 ],
        [ 'name'=>'Marcos Paz','state_id'=>1818 ],
        [ 'name'=>'Abbott','state_id'=>1818 ],
        [ 'name'=>'San Miguel del Monte','state_id'=>1818 ],
        [ 'name'=>'Zenón Videla Dorna','state_id'=>1818 ],
        [ 'name'=>'Navarro','state_id'=>1818 ],
        [ 'name'=>'Carlos Beguerie','state_id'=>1818 ],
        [ 'name'=>'Azul','state_id'=>1818 ],
        [ 'name'=>'Cacharí','state_id'=>1818 ],
        [ 'name'=>'Balcarce','state_id'=>1818 ],
        [ 'name'=>'Los Pinos','state_id'=>1818 ],
        [ 'name'=>'San Agustín','state_id'=>1818 ],
        [ 'name'=>'López','state_id'=>1818 ],
        [ 'name'=>'Tedín Uriburu','state_id'=>1818 ],
        [ 'name'=>'Villa Cacique','state_id'=>1818 ],
        [ 'name'=>'Centro Guerrero','state_id'=>1818 ],
        [ 'name'=>'Cerro de la Gloria','state_id'=>1818 ],
        [ 'name'=>'Dolores','state_id'=>1818 ],
        [ 'name'=>'Sevigne','state_id'=>1818 ],
        [ 'name'=>'Comandante Nicanor Otamendi','state_id'=>1818 ],
        [ 'name'=>'Mechongué','state_id'=>1818 ],
        [ 'name'=>'General Guido','state_id'=>1818 ],
        [ 'name'=>'Labardén','state_id'=>1818 ],
        [ 'name'=>'Pavón','state_id'=>1818 ],
        [ 'name'=>'El Marquesado','state_id'=>1818 ],
        [ 'name'=>'Sierra de los Padres','state_id'=>1818 ],
        [ 'name'=>'Coronel Boerr','state_id'=>1818 ],
        [ 'name'=>'El Trigo','state_id'=>1818 ],
        [ 'name'=>'Las Flores','state_id'=>1818 ],
        [ 'name'=>'Pardo','state_id'=>1818 ],
        [ 'name'=>'Licenciado Matienzo','state_id'=>1818 ],
        [ 'name'=>'San Manuel','state_id'=>1818 ],
        [ 'name'=>'Las Armas','state_id'=>1818 ],
        [ 'name'=>'General Pirán','state_id'=>1818 ],
        [ 'name'=>'Mar de Cobo','state_id'=>1818 ],
        [ 'name'=>'Vivoratá','state_id'=>1818 ],
        [ 'name'=>'Claraz','state_id'=>1818 ],
        [ 'name'=>'Juan N. Fernández','state_id'=>1818 ],
        [ 'name'=>'Nicanor Olivera','state_id'=>1818 ],
        [ 'name'=>'Pila','state_id'=>1818 ],
        [ 'name'=>'Pinamar','state_id'=>1818 ],
        [ 'name'=>'Rauch','state_id'=>1818 ],
        [ 'name'=>'De la Canal','state_id'=>1818 ],
        [ 'name'=>'Tandil','state_id'=>1818 ],
        [ 'name'=>'Velloso','state_id'=>1818 ],
        [ 'name'=>'General Conesa','state_id'=>1818 ],
        [ 'name'=>'Villa Gesell','state_id'=>1818 ],
        [ 'name'=>'San Carlos de Bolívar','state_id'=>1818 ],
        [ 'name'=>'La Armonía','state_id'=>1818 ],
        [ 'name'=>'Barrio Los Pioneros (Barrio Tavella)','state_id'=>1818 ],
        [ 'name'=>'Campana','state_id'=>1818 ],
        [ 'name'=>'Escobar','state_id'=>1818 ],
        [ 'name'=>'Capilla del Señor','state_id'=>1818 ],
        [ 'name'=>'Diego Gaynor','state_id'=>1818 ],
        [ 'name'=>'Los Cardales','state_id'=>1818 ],
        [ 'name'=>'Parada Robles - Pavón','state_id'=>1818 ],
        [ 'name'=>'La Choza','state_id'=>1818 ],
        [ 'name'=>'Plomer','state_id'=>1818 ],
        [ 'name'=>'General Rodríguez','state_id'=>1818 ],
        [ 'name'=>'General San Martín','state_id'=>1818 ],
        [ 'name'=>'Hurlingham','state_id'=>1818 ],
        [ 'name'=>'Ituzaingó','state_id'=>1818 ],
        [ 'name'=>'José C. Paz','state_id'=>1818 ],
        [ 'name'=>'La Matanza','state_id'=>1818 ],
        [ 'name'=>'Carlos Keen','state_id'=>1818 ],
        [ 'name'=>'Club de Campo Los Puentes','state_id'=>1818 ],
        [ 'name'=>'Luján','state_id'=>1818 ],
        [ 'name'=>'Olivera','state_id'=>1818 ],
        [ 'name'=>'Torres','state_id'=>1818 ],
        [ 'name'=>'Malvinas Argentinas','state_id'=>1818 ],
        [ 'name'=>'Goldney','state_id'=>1818 ],
        [ 'name'=>'Jorge Born','state_id'=>1818 ],
        [ 'name'=>'Merlo','state_id'=>1818 ],
        [ 'name'=>'Moreno','state_id'=>1818 ],
        [ 'name'=>'Morón','state_id'=>1818 ],
        [ 'name'=>'Pilar','state_id'=>1818 ],
        [ 'name'=>'Solís','state_id'=>1818 ],
        [ 'name'=>'Villa Ruiz','state_id'=>1818 ],
        [ 'name'=>'San Fernando','state_id'=>1818 ],
        [ 'name'=>'San Isidro','state_id'=>1818 ],
        [ 'name'=>'San Miguel','state_id'=>1818 ],
        [ 'name'=>'Tigre','state_id'=>1818 ],
        [ 'name'=>'Tres de Febrero','state_id'=>1818 ],
        [ 'name'=>'Vicente López','state_id'=>1818 ],
        [ 'name'=>'Pieres','state_id'=>1818 ],
        [ 'name'=>'Lima','state_id'=>1818 ],
        [ 'name'=>'Zárate','state_id'=>1818 ],
        [ 'name'=>'Santa Clara del Mar','state_id'=>1818 ],
        [ 'name'=>'Colón','state_id'=>1818 ],
        [ 'name'=>'Sarasa','state_id'=>1818 ],
        [ 'name'=>'Arribeños','state_id'=>1818 ],
        [ 'name'=>'Ascensión','state_id'=>1818 ],
        [ 'name'=>'Estación Arenales','state_id'=>1818 ],
        [ 'name'=>'Ferré','state_id'=>1818 ],
        [ 'name'=>'General Arenales','state_id'=>1818 ],
        [ 'name'=>'Colonia San Ricardo','state_id'=>1818 ],
        [ 'name'=>'Germania','state_id'=>1818 ],
        [ 'name'=>'Gunther','state_id'=>1818 ],
        [ 'name'=>'Villa Roth','state_id'=>1818 ],
        [ 'name'=>'Fortín Tiburcio','state_id'=>1818 ],
        [ 'name'=>'Saforcada','state_id'=>1818 ],
        [ 'name'=>'Alberdi Viejo','state_id'=>1818 ],
        [ 'name'=>'Fortín Acha','state_id'=>1818 ],
        [ 'name'=>'Juan Bautista Alberdi','state_id'=>1818 ],
        [ 'name'=>'Leandro N. Alem','state_id'=>1818 ],
        [ 'name'=>'Vedia','state_id'=>1818 ],
        [ 'name'=>'Bermúdez','state_id'=>1818 ],
        [ 'name'=>'Berazategui','state_id'=>1818 ],
        [ 'name'=>'Berisso','state_id'=>1818 ],
        [ 'name'=>'Altamirano','state_id'=>1818 ],
        [ 'name'=>'Barrio El Mirador','state_id'=>1818 ],
        [ 'name'=>'Barrio Las Golondrinas','state_id'=>1818 ],
        [ 'name'=>'Barrio Los Bosquecitos','state_id'=>1818 ],
        [ 'name'=>'Campos de Roca','state_id'=>1818 ],
        [ 'name'=>'Coronel Brandsen','state_id'=>1818 ],
        [ 'name'=>'Gómez','state_id'=>1818 ],
        [ 'name'=>'Jeppener','state_id'=>1818 ],
        [ 'name'=>'Oliden','state_id'=>1818 ],
        [ 'name'=>'Barrio Lomas Altas','state_id'=>1818 ],
        [ 'name'=>'Chascomús','state_id'=>1818 ],
        [ 'name'=>'Laguna Vitel','state_id'=>1818 ],
        [ 'name'=>'Manuel J. Cobo','state_id'=>1818 ],
        [ 'name'=>'Villa Parque Girado','state_id'=>1818 ],
        [ 'name'=>'Ensenada','state_id'=>1818 ],
        [ 'name'=>'La Plata','state_id'=>1818 ],
        [ 'name'=>'Atalaya','state_id'=>1818 ],
        [ 'name'=>'General Mansilla','state_id'=>1818 ],
        [ 'name'=>'Los Naranjos','state_id'=>1818 ],
        [ 'name'=>'Magdalena','state_id'=>1818 ],
        [ 'name'=>'Vieytes','state_id'=>1818 ],
        [ 'name'=>'Alvarez Jonte','state_id'=>1818 ],
        [ 'name'=>'Pipinas','state_id'=>1818 ],
        [ 'name'=>'Punta Indio','state_id'=>1818 ],
        [ 'name'=>'Verónica','state_id'=>1818 ],
        [ 'name'=>'Avellaneda','state_id'=>1818 ],
        [ 'name'=>'Lanús','state_id'=>1818 ],
        [ 'name'=>'Quilmes','state_id'=>1818 ],
        [ 'name'=>'Cadret','state_id'=>1818 ],
        [ 'name'=>'Carlos Casares','state_id'=>1818 ],
        [ 'name'=>'Colonia Mauricio','state_id'=>1818 ],
        [ 'name'=>'La Sofía','state_id'=>1818 ],
        [ 'name'=>'Mauricio Hirsch','state_id'=>1818 ],
        [ 'name'=>'Moctezuma','state_id'=>1818 ],
        [ 'name'=>'Ordoqui','state_id'=>1818 ],
        [ 'name'=>'Santo Tomás','state_id'=>1818 ],
        [ 'name'=>'Smith','state_id'=>1818 ],
        [ 'name'=>'La Delfina','state_id'=>1818 ],
        [ 'name'=>'Laplacette','state_id'=>1818 ],
        [ 'name'=>'El Dorado','state_id'=>1818 ],
        [ 'name'=>'Bayauca','state_id'=>1818 ],
        [ 'name'=>'Coronel Martínez de Hoz','state_id'=>1818 ],
        [ 'name'=>'El Triunfo','state_id'=>1818 ],
        [ 'name'=>'Lincoln','state_id'=>1818 ],
        [ 'name'=>'Triunvirato','state_id'=>1818 ],
        [ 'name'=>'Alfredo Demarchi','state_id'=>1818 ],
        [ 'name'=>'Casalins','state_id'=>1818 ],
        [ 'name'=>'La Aurora','state_id'=>1818 ],
        [ 'name'=>'San Bernardo','state_id'=>1818 ],
        [ 'name'=>'Alberti','state_id'=>1818 ],
        [ 'name'=>'Coronel Seguí','state_id'=>1818 ],
        [ 'name'=>'Mechita','state_id'=>1818 ],
        [ 'name'=>'Pla','state_id'=>1818 ],
        [ 'name'=>'Villa Grisolía','state_id'=>1818 ],
        [ 'name'=>'Villa María','state_id'=>1818 ],
        [ 'name'=>'Villa Ortiz','state_id'=>1818 ],
        [ 'name'=>'Bragado','state_id'=>1818 ],
        [ 'name'=>'Comodoro Py','state_id'=>1818 ],
        [ 'name'=>"General O'Brien",'state_id'=>1818 ],
        [ 'name'=>'Irala','state_id'=>1818 ],
        [ 'name'=>'La Limpia','state_id'=>1818 ],
        [ 'name'=>'Juan F. Salaberry','state_id'=>1818 ],
        [ 'name'=>'Mechita','state_id'=>1818 ],
        [ 'name'=>'Olascoaga','state_id'=>1818 ],
        [ 'name'=>'Warnes','state_id'=>1818 ],
        [ 'name'=>'Benitez','state_id'=>1818 ],
        [ 'name'=>'Chivilcoy','state_id'=>1818 ],
        [ 'name'=>'Emilio Ayarza','state_id'=>1818 ],
        [ 'name'=>'Gorostiaga','state_id'=>1818 ],
        [ 'name'=>'La Rica','state_id'=>1818 ],
        [ 'name'=>'Moquehuá','state_id'=>1818 ],
        [ 'name'=>'Ramón Biaus','state_id'=>1818 ],
        [ 'name'=>'San Sebastián','state_id'=>1818 ],
        [ 'name'=>'Baigorrita','state_id'=>1818 ],
        [ 'name'=>'Los Toldos','state_id'=>1818 ],
        [ 'name'=>'San Emilio','state_id'=>1818 ],
        [ 'name'=>'Zavalía','state_id'=>1818 ],
        [ 'name'=>'Agustina','state_id'=>1818 ],
        [ 'name'=>'Junín','state_id'=>1818 ],
        [ 'name'=>'Morse','state_id'=>1818 ],
        [ 'name'=>'Antonio Carboni','state_id'=>1818 ],
        [ 'name'=>'Elvira','state_id'=>1818 ],
        [ 'name'=>'Mercedes','state_id'=>1818 ],
        [ 'name'=>'Morea','state_id'=>1818 ],
        [ 'name'=>'José Juan Almeyra','state_id'=>1818 ],
        [ 'name'=>'Las Marianas','state_id'=>1818 ],
        [ 'name'=>'Villa Moll','state_id'=>1818 ],
        [ 'name'=>'Carlos María Naón','state_id'=>1818 ],
        [ 'name'=>'12 de Octubre','state_id'=>1818 ],
        [ 'name'=>'Dudignac','state_id'=>1818 ],
        [ 'name'=>'Manuel B. Gonnet','state_id'=>1818 ],
        [ 'name'=>'Marcelino Ugarte','state_id'=>1818 ],
        [ 'name'=>'Norumbega','state_id'=>1818 ],
        [ 'name'=>'9 de Julio','state_id'=>1818 ],
        [ 'name'=>'Patricios','state_id'=>1818 ],
        [ 'name'=>'Roque Pérez','state_id'=>1818 ],
        [ 'name'=>'Álvarez de Toledo','state_id'=>1818 ],
        [ 'name'=>'Cazón','state_id'=>1818 ],
        [ 'name'=>'Del Carril','state_id'=>1818 ],
        [ 'name'=>'Polvaredas','state_id'=>1818 ],
        [ 'name'=>'Saladillo','state_id'=>1818 ],
        [ 'name'=>'Cucullú','state_id'=>1818 ],
        [ 'name'=>'San Andrés de Giles','state_id'=>1818 ],
        [ 'name'=>'Villa Espil','state_id'=>1818 ],
        [ 'name'=>'Suipacha','state_id'=>1818 ],
        [ 'name'=>'Agustín Mosconi','state_id'=>1818 ],
        [ 'name'=>'Del Valle','state_id'=>1818 ],
        [ 'name'=>'Ernestina','state_id'=>1818 ],
        [ 'name'=>'Gobernador Ugarte','state_id'=>1818 ],
        [ 'name'=>'Lucas Monteverde','state_id'=>1818 ],
        [ 'name'=>'Norberto de la Riestra','state_id'=>1818 ],
        [ 'name'=>'Pedernales','state_id'=>1818 ],
        [ 'name'=>'San Enrique','state_id'=>1818 ],
        [ 'name'=>'Valdés','state_id'=>1818 ],
        [ 'name'=>'25 de Mayo','state_id'=>1818 ],
        [ 'name'=>'Hale','state_id'=>1818 ],
        [ 'name'=>'Adolfo Gonzales Chaves','state_id'=>1818 ],
        [ 'name'=>'Juan E. Barra','state_id'=>1818 ],
        [ 'name'=>'Vásquez','state_id'=>1818 ],
        [ 'name'=>'Ariel','state_id'=>1818 ],
        [ 'name'=>'Chillar','state_id'=>1818 ],
        [ 'name'=>'Benito Juárez','state_id'=>1818 ],
        [ 'name'=>'Energía','state_id'=>1818 ],
        [ 'name'=>'Colonia Nievas','state_id'=>1818 ],
        [ 'name'=>'Olavarría','state_id'=>1818 ],
        [ 'name'=>'Santa Luisa','state_id'=>1818 ],
        [ 'name'=>'Sierra Chica','state_id'=>1818 ],
        [ 'name'=>'Balneario San Cayetano','state_id'=>1818 ],
        [ 'name'=>'Ochandío','state_id'=>1818 ],
        [ 'name'=>'San Cayetano','state_id'=>1818 ],
        [ 'name'=>'Gardey','state_id'=>1818 ],
        [ 'name'=>'María Ignacia','state_id'=>1818 ],
        [ 'name'=>'Claromecó','state_id'=>1818 ],
        [ 'name'=>'Copetonas','state_id'=>1818 ],
        [ 'name'=>'Micaela Cascallares','state_id'=>1818 ],
        [ 'name'=>'Orense','state_id'=>1818 ],
        [ 'name'=>'San Francisco de Bellocq','state_id'=>1818 ],
        [ 'name'=>'Tres Arroyos','state_id'=>1818 ],
        [ 'name'=>'Villa Rodríguez','state_id'=>1818 ],
        [ 'name'=>'Castelli','state_id'=>1818 ],
        [ 'name'=>'Mar del Sur','state_id'=>1818 ],
        [ 'name'=>'Urdampilleta','state_id'=>1818 ],
        [ 'name'=>'Bahía Blanca','state_id'=>1818 ],
        [ 'name'=>'Cabildo','state_id'=>1818 ],
        [ 'name'=>'General Daniel Cerri','state_id'=>1818 ],
        [ 'name'=>'Balneario Pehuen Co','state_id'=>1818 ],
        [ 'name'=>'Marisol','state_id'=>1818 ],
        [ 'name'=>'San Román','state_id'=>1818 ],
        [ 'name'=>'Lartigau','state_id'=>1818 ],
        [ 'name'=>'Centinela del Mar','state_id'=>1818 ],
        [ 'name'=>'Balneario Sauce Grande','state_id'=>1818 ],
        [ 'name'=>'Monte Hermoso','state_id'=>1818 ],
        [ 'name'=>'Necochea - Quequén','state_id'=>1818 ],
        [ 'name'=>'Ramón Santamarina','state_id'=>1818 ],
        [ 'name'=>'Bahía San Blas','state_id'=>1818 ],
        [ 'name'=>'Cardenal Cagliero','state_id'=>1818 ],
        [ 'name'=>'Carmen de Patagones','state_id'=>1818 ],
        [ 'name'=>'José B. Casas','state_id'=>1818 ],
        [ 'name'=>'Juan A. Pradere','state_id'=>1818 ],
        [ 'name'=>'Stroeder','state_id'=>1818 ],
        [ 'name'=>'Villalonga','state_id'=>1818 ],
        [ 'name'=>'Balneario Orense','state_id'=>1818 ],
        [ 'name'=>'Reta','state_id'=>1818 ],
        [ 'name'=>'Argerich','state_id'=>1818 ],
        [ 'name'=>'Hilario Ascasubi','state_id'=>1818 ],
        [ 'name'=>'Mayor Buratovich','state_id'=>1818 ],
        [ 'name'=>'Médanos','state_id'=>1818 ],
        [ 'name'=>'Pedro Luro','state_id'=>1818 ],
        [ 'name'=>'Teniente Origone','state_id'=>1818 ],
        [ 'name'=>'Almirante Brown','state_id'=>1818 ],
        [ 'name'=>'Barrio Parque Las Acacias','state_id'=>1818 ],
        [ 'name'=>'Gobernador Udaondo','state_id'=>1818 ],
        [ 'name'=>'Máximo Paz','state_id'=>1818 ],
        [ 'name'=>'Esteban Echeverría','state_id'=>1818 ],
        [ 'name'=>'Ezeiza','state_id'=>1818 ],
        [ 'name'=>'Florencio Varela','state_id'=>1818 ],
        [ 'name'=>'General Belgrano','state_id'=>1818 ],
        [ 'name'=>'Loma Verde','state_id'=>1818 ],
        [ 'name'=>'Ranchos','state_id'=>1818 ],
        [ 'name'=>'Villanueva','state_id'=>1818 ],
        [ 'name'=>'Lomas de Zamora','state_id'=>1818 ],
        [ 'name'=>'Presidente Perón','state_id'=>1818 ],
        [ 'name'=>'San Vicente','state_id'=>1818 ],
        [ 'name'=>'Carlos Tejedor','state_id'=>1818 ],
        [ 'name'=>'Colonia Seré','state_id'=>1818 ],
        [ 'name'=>'Curarú','state_id'=>1818 ],
        [ 'name'=>'Timote','state_id'=>1818 ],
        [ 'name'=>'Tres Algarrobos','state_id'=>1818 ],
        [ 'name'=>'Blaquier','state_id'=>1818 ],
        [ 'name'=>'Florentino Ameghino','state_id'=>1818 ],
        [ 'name'=>'Porvenir','state_id'=>1818 ],
        [ 'name'=>'General Pinto','state_id'=>1818 ],
        [ 'name'=>'Villa Francia','state_id'=>1818 ],
        [ 'name'=>'Banderaló','state_id'=>1818 ],
        [ 'name'=>'Cañada Seca','state_id'=>1818 ],
        [ 'name'=>'Coronel Charlone','state_id'=>1818 ],
        [ 'name'=>'Emilio V. Bunge','state_id'=>1818 ],
        [ 'name'=>'General Villegas','state_id'=>1818 ],
        [ 'name'=>'Massey','state_id'=>1818 ],
        [ 'name'=>'Pichincha','state_id'=>1818 ],
        [ 'name'=>'Piedritas','state_id'=>1818 ],
        [ 'name'=>'Santa Eleodora','state_id'=>1818 ],
        [ 'name'=>'Santa Regina','state_id'=>1818 ],
        [ 'name'=>'Villa Saboya','state_id'=>1818 ],
        [ 'name'=>'Villa Sauze','state_id'=>1818 ],
        [ 'name'=>'Arenaza','state_id'=>1818 ],
        [ 'name'=>'Carlos Salas','state_id'=>1818 ],
        [ 'name'=>'Las Toscas','state_id'=>1818 ],
        [ 'name'=>'Pasteur','state_id'=>1818 ],
        [ 'name'=>'Roberts','state_id'=>1818 ],
        [ 'name'=>'San Esteban','state_id'=>1818 ],
        [ 'name'=>'Inocencio Sosa','state_id'=>1818 ],
        [ 'name'=>'América','state_id'=>1818 ],
        [ 'name'=>'Fortín Olavarría','state_id'=>1818 ],
        [ 'name'=>'González Moreno','state_id'=>1818 ],
        [ 'name'=>'Mira Pampa','state_id'=>1818 ],
        [ 'name'=>'Roosevelt','state_id'=>1818 ],
        [ 'name'=>'San Mauricio','state_id'=>1818 ],
        [ 'name'=>'Sansinena','state_id'=>1818 ],
        [ 'name'=>'Sundblad','state_id'=>1818 ],
        [ 'name'=>'Trenque Lauquen','state_id'=>1818 ],
        [ 'name'=>'Lobería','state_id'=>1818 ],
        [ 'name'=>'De La Garma','state_id'=>1818 ],
        [ 'name'=>'Colonia San Miguel Arcángel','state_id'=>1818 ],
        [ 'name'=>'Delfín Huergo','state_id'=>1818 ],
        [ 'name'=>'Esteban Agustín Gascón','state_id'=>1818 ],
        [ 'name'=>'La Pala','state_id'=>1818 ],
        [ 'name'=>'Maza','state_id'=>1818 ],
        [ 'name'=>'Rivera','state_id'=>1818 ],
        [ 'name'=>'Yutuyaco','state_id'=>1818 ],
        [ 'name'=>'Juan F. Ibarra','state_id'=>1818 ],
        [ 'name'=>'Paula','state_id'=>1818 ],
        [ 'name'=>'Pirovano','state_id'=>1818 ],
        [ 'name'=>'El Pensamiento','state_id'=>1818 ],
        [ 'name'=>'Indio Rico','state_id'=>1818 ],
        [ 'name'=>'Coronel Suárez','state_id'=>1818 ],
        [ 'name'=>'Huanguelén','state_id'=>1818 ],
        [ 'name'=>'Villa La Arcadia','state_id'=>1818 ],
        [ 'name'=>'Daireaux','state_id'=>1818 ],
        [ 'name'=>'La Colina','state_id'=>1818 ],
        [ 'name'=>'Las Martinetas','state_id'=>1818 ],
        [ 'name'=>'Líbano','state_id'=>1818 ],
        [ 'name'=>'Arroyo Venado','state_id'=>1818 ],
        [ 'name'=>'Guaminí','state_id'=>1818 ],
        [ 'name'=>'Laprida','state_id'=>1818 ],
        [ 'name'=>'Pueblo Nuevo','state_id'=>1818 ],
        [ 'name'=>'Pueblo San Jorge','state_id'=>1818 ],
        [ 'name'=>'Blancagrande','state_id'=>1818 ],
        [ 'name'=>'Espigas','state_id'=>1818 ],
        [ 'name'=>'Magdala','state_id'=>1818 ],
        [ 'name'=>'Mones Cazón','state_id'=>1818 ],
        [ 'name'=>'Bocayuva','state_id'=>1818 ],
        [ 'name'=>'De Bary','state_id'=>1818 ],
        [ 'name'=>'Pellegrini','state_id'=>1818 ],
        [ 'name'=>'Azopardo','state_id'=>1818 ],
        [ 'name'=>'Bordenave','state_id'=>1818 ],
        [ 'name'=>'Darregueira','state_id'=>1818 ],
        [ 'name'=>'Estela','state_id'=>1818 ],
        [ 'name'=>'Felipe Solá','state_id'=>1818 ],
        [ 'name'=>'López Lecube','state_id'=>1818 ],
        [ 'name'=>'Puán','state_id'=>1818 ],
        [ 'name'=>'San Germán','state_id'=>1818 ],
        [ 'name'=>'Villa Iris','state_id'=>1818 ],
        [ 'name'=>'Colonia San Martín','state_id'=>1818 ],
        [ 'name'=>'Dufaur','state_id'=>1818 ],
        [ 'name'=>'Espartillar','state_id'=>1818 ],
        [ 'name'=>'Saavedra','state_id'=>1818 ],
        [ 'name'=>'Quenumá','state_id'=>1818 ],
        [ 'name'=>'Salliqueló','state_id'=>1818 ],
        [ 'name'=>'Chasicó','state_id'=>1818 ],
        [ 'name'=>'Saldungaray','state_id'=>1818 ],
        [ 'name'=>'Tornquist','state_id'=>1818 ],
        [ 'name'=>'Villa Ventana','state_id'=>1818 ],
        [ 'name'=>'Trongé','state_id'=>1818 ],
        [ 'name'=>'Tres Lomas','state_id'=>1818 ],
        [ 'name'=>'Santo Domingo','state_id'=>1818 ],
        [ 'name'=>'Coronel Vidal','state_id'=>1818 ],
        [ 'name'=>'Bajo Hondo','state_id'=>1818 ],
        [ 'name'=>'Punta Alta','state_id'=>1818 ],
        [ 'name'=>'Aparicio','state_id'=>1818 ],
        [ 'name'=>'Coronel Dorrego','state_id'=>1818 ],
        [ 'name'=>'El Perdido','state_id'=>1818 ],
        [ 'name'=>'Faro','state_id'=>1818 ],
        [ 'name'=>'Irene','state_id'=>1818 ],
        [ 'name'=>'Oriente','state_id'=>1818 ],
        [ 'name'=>'Paraje La Ruta','state_id'=>1818 ],
        [ 'name'=>'Country Los Medanos','state_id'=>1818 ],
        [ 'name'=>'Juan Cousté','state_id'=>1818 ],
        [ 'name'=>'San Nicolás de los Arroyos','state_id'=>1818 ],
        [ 'name'=>'Rojas','state_id'=>1818 ],
        [ 'name'=>'Irineo Portela','state_id'=>1818 ],
        [ 'name'=>'Santa Coloma','state_id'=>1818 ],
        [ 'name'=>'Arrecifes','state_id'=>1818 ],
        [ 'name'=>'Viña','state_id'=>1818 ],
        [ 'name'=>'Capitán Sarmiento','state_id'=>1818 ],
        [ 'name'=>'La Luisa','state_id'=>1818 ],
        [ 'name'=>'Carmen de Areco','state_id'=>1818 ],
        [ 'name'=>'Pueblo Gouin','state_id'=>1818 ],
        [ 'name'=>'Tres Sargentos','state_id'=>1818 ],
        [ 'name'=>'Villa Manuel Pomar','state_id'=>1818 ],
        [ 'name'=>'Pearson','state_id'=>1818 ],
        [ 'name'=>'Castilla','state_id'=>1818 ],
        [ 'name'=>'Chacabuco','state_id'=>1818 ],
        [ 'name'=>'Los Angeles','state_id'=>1818 ],
        [ 'name'=>"O'Higgins",'state_id'=>1818 ],
        [ 'name'=>'Rawson','state_id'=>1818 ],
        [ 'name'=>'La Angelita','state_id'=>1818 ],
        [ 'name'=>'Agustín Roca','state_id'=>1818 ],
        [ 'name'=>'Paraje La Agraria','state_id'=>1818 ],
        [ 'name'=>'Acevedo','state_id'=>1818 ],
        [ 'name'=>'Fontezuela','state_id'=>1818 ],
        [ 'name'=>'Guerrico','state_id'=>1818 ],
        [ 'name'=>'Juan A. de la Peña','state_id'=>1818 ],
        [ 'name'=>'Juan Anchorena','state_id'=>1818 ],
        [ 'name'=>'La Violeta','state_id'=>1818 ],
        [ 'name'=>'Manuel Ocampo','state_id'=>1818 ],
        [ 'name'=>'Mariano Benítez','state_id'=>1818 ],
        [ 'name'=>'Mariano H. Alfonzo','state_id'=>1818 ],
        [ 'name'=>'Pergamino','state_id'=>1818 ],
        [ 'name'=>'Pinzón','state_id'=>1818 ],
        [ 'name'=>'Rancagua','state_id'=>1818 ],
        [ 'name'=>'Villa Angélica','state_id'=>1818 ],
        [ 'name'=>'Villa San José','state_id'=>1818 ],
        [ 'name'=>'Tamangueyú','state_id'=>1818 ],
        [ 'name'=>'Mar Chiquita','state_id'=>1818 ],
        [ 'name'=>'16 de Julio','state_id'=>1818 ],
        [ 'name'=>'El Paraíso','state_id'=>1818 ],
        [ 'name'=>'Las Bahamas','state_id'=>1818 ],
        [ 'name'=>'Pérez Millán','state_id'=>1818 ],
        [ 'name'=>'Ramallo','state_id'=>1818 ],
        [ 'name'=>'Villa General Savio','state_id'=>1818 ],
        [ 'name'=>'La Beba','state_id'=>1818 ],
        [ 'name'=>'Las Carabelas','state_id'=>1818 ],
        [ 'name'=>'Los Indios','state_id'=>1818 ],
        [ 'name'=>'Rafael Obligado','state_id'=>1818 ],
        [ 'name'=>'Roberto Cano','state_id'=>1818 ],
        [ 'name'=>'Sol de Mayo','state_id'=>1818 ],
        [ 'name'=>'Villa Manuel Pomar','state_id'=>1818 ],
        [ 'name'=>'Obligado','state_id'=>1818 ],
        [ 'name'=>'Arroyo Dulce','state_id'=>1818 ],
        [ 'name'=>'Berdier','state_id'=>1818 ],
        [ 'name'=>'Gahan','state_id'=>1818 ],
        [ 'name'=>'Inés Indart','state_id'=>1818 ],
        [ 'name'=>'La Invencible','state_id'=>1818 ],
        [ 'name'=>'Salto','state_id'=>1818 ],
        [ 'name'=>'Franklin','state_id'=>1818 ],
        [ 'name'=>'Duggan','state_id'=>1818 ],
        [ 'name'=>'Conesa','state_id'=>1818 ],
        [ 'name'=>'Erezcano','state_id'=>1818 ],
        [ 'name'=>'General Rojo','state_id'=>1818 ],
        [ 'name'=>'Villa Esperanza','state_id'=>1818 ],
        [ 'name'=>'Gobernador Castro','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Moneta','state_id'=>1818 ],
        [ 'name'=>'Pueblo Doyle','state_id'=>1818 ],
        [ 'name'=>'Río Tala','state_id'=>1818 ],
        [ 'name'=>'San Pedro','state_id'=>1818 ],
        [ 'name'=>'Santa Lucía','state_id'=>1818 ],
        [ 'name'=>'General Rivas','state_id'=>1818 ],
        [ 'name'=>'Baradero','state_id'=>1818 ],
        [ 'name'=>'Villa Alsina','state_id'=>1818 ],
        [ 'name'=>'Azcuénaga','state_id'=>1818 ],
        [ 'name'=>'San Antonio de Areco','state_id'=>1818 ],
        [ 'name'=>'Villa Lía','state_id'=>1818 ],
        [ 'name'=>'Ayacucho','state_id'=>1818 ],
        [ 'name'=>'La Constancia','state_id'=>1818 ],
        [ 'name'=>'Solanet','state_id'=>1818 ],
        [ 'name'=>'Udaquiola','state_id'=>1818 ],
        [ 'name'=>'Napaleofú','state_id'=>1818 ],
        [ 'name'=>'Ramos Otero','state_id'=>1818 ],
        [ 'name'=>'Villa Laguna La Brava','state_id'=>1818 ],
        [ 'name'=>'Miramar','state_id'=>1818 ],
        [ 'name'=>'General Juan Madariaga','state_id'=>1818 ],
        [ 'name'=>'General Lavalle','state_id'=>1818 ],
        [ 'name'=>'Barrio El Boquerón','state_id'=>1818 ],
        [ 'name'=>'Barrio Santa Paula','state_id'=>1818 ],
        [ 'name'=>'Chapadmalal','state_id'=>1818 ],
        [ 'name'=>'Mar del Plata','state_id'=>1818 ],
        [ 'name'=>'San Clemente del Tuyú','state_id'=>1818 ],
        [ 'name'=>'Santa Teresita - Mar del Tuyú','state_id'=>1818 ],
        [ 'name'=>'Arenas Verdes','state_id'=>1818 ],
        [ 'name'=>'Maipú','state_id'=>1818 ],
        [ 'name'=>'Pontaut','state_id'=>1818 ],
        [ 'name'=>'Carhué','state_id'=>1818 ],
        [ 'name'=>'Espartillar','state_id'=>1818 ],
        [ 'name'=>'Merlo','state_id'=>1818 ],
        [ 'name'=>'Villa Bordeau','state_id'=>1818 ],
        [ 'name'=>'Berazategui','state_id'=>1818 ],
        [ 'name'=>'Berazategui Oeste','state_id'=>1818 ],
        [ 'name'=>'Carlos Tomás Sourigues','state_id'=>1818 ],
        [ 'name'=>'El Pato','state_id'=>1818 ],
        [ 'name'=>'Guillermo Enrique Hudson','state_id'=>1818 ],
        [ 'name'=>'Juan María Gutiérrez','state_id'=>1818 ],
        [ 'name'=>'Pereyra','state_id'=>1818 ],
        [ 'name'=>'Plátanos','state_id'=>1818 ],
        [ 'name'=>'Ranelagh','state_id'=>1818 ],
        [ 'name'=>'Villa España','state_id'=>1818 ],
        [ 'name'=>'Barrio Banco Provincia','state_id'=>1818 ],
        [ 'name'=>'Barrio El Carmen Este','state_id'=>1818 ],
        [ 'name'=>'Barrio Universitario','state_id'=>1818 ],
        [ 'name'=>'Berisso','state_id'=>1818 ],
        [ 'name'=>'Los Talas','state_id'=>1818 ],
        [ 'name'=>'Villa Argüello','state_id'=>1818 ],
        [ 'name'=>'Villa Dolores','state_id'=>1818 ],
        [ 'name'=>'Villa Independencia','state_id'=>1818 ],
        [ 'name'=>'Villa Porteña','state_id'=>1818 ],
        [ 'name'=>'Villa Progreso','state_id'=>1818 ],
        [ 'name'=>'Villa San Carlos','state_id'=>1818 ],
        [ 'name'=>'Villa Zula','state_id'=>1818 ],
        [ 'name'=>'Barrio Belgrano','state_id'=>1818 ],
        [ 'name'=>'Máximo Paz','state_id'=>1818 ],
        [ 'name'=>'Punta Alta','state_id'=>1818 ],
        [ 'name'=>'Villa del Mar','state_id'=>1818 ],
        [ 'name'=>'Chascomús','state_id'=>1818 ],
        [ 'name'=>'Barrio San Cayetano','state_id'=>1818 ],
        [ 'name'=>'Dique N° 1','state_id'=>1818 ],
        [ 'name'=>'Ensenada','state_id'=>1818 ],
        [ 'name'=>'Burzaco','state_id'=>1818 ],
        [ 'name'=>'Claypole','state_id'=>1818 ],
        [ 'name'=>'Don Orione','state_id'=>1818 ],
        [ 'name'=>'Glew','state_id'=>1818 ],
        [ 'name'=>'José Mármol','state_id'=>1818 ],
        [ 'name'=>'Longchamps','state_id'=>1818 ],
        [ 'name'=>'Rafael Calzada','state_id'=>1818 ],
        [ 'name'=>'San Francisco Solano','state_id'=>1818 ],
        [ 'name'=>'San José','state_id'=>1818 ],
        [ 'name'=>'Gerli','state_id'=>1818 ],
        [ 'name'=>'Piñeyro','state_id'=>1818 ],
        [ 'name'=>'Sarandí','state_id'=>1818 ],
        [ 'name'=>'Villa Domínico','state_id'=>1818 ],
        [ 'name'=>'Wilde','state_id'=>1818 ],
        [ 'name'=>'Área Reserva Cinturón Ecológico','state_id'=>1818 ],
        [ 'name'=>'Avellaneda','state_id'=>1818 ],
        [ 'name'=>'Crucesita','state_id'=>1818 ],
        [ 'name'=>'Dock Sud','state_id'=>1818 ],
        [ 'name'=>'Bahía Blanca','state_id'=>1818 ],
        [ 'name'=>'Grünbein','state_id'=>1818 ],
        [ 'name'=>'Ingeniero White','state_id'=>1818 ],
        [ 'name'=>'Isla Santiago','state_id'=>1818 ],
        [ 'name'=>'Punta Lara','state_id'=>1818 ],
        [ 'name'=>'Villa Catela','state_id'=>1818 ],
        [ 'name'=>'Belén de Escobar','state_id'=>1818 ],
        [ 'name'=>'El Cazador','state_id'=>1818 ],
        [ 'name'=>'Garín','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Maschwitz','state_id'=>1818 ],
        [ 'name'=>'Loma Verde','state_id'=>1818 ],
        [ 'name'=>'Matheu','state_id'=>1818 ],
        [ 'name'=>'Maquinista F. Savio Este','state_id'=>1818 ],
        [ 'name'=>'Canning','state_id'=>1818 ],
        [ 'name'=>'El Jagüel','state_id'=>1818 ],
        [ 'name'=>'Malvinas Argentinas','state_id'=>1818 ],
        [ 'name'=>'Ministro Rivadavia','state_id'=>1818 ],
        [ 'name'=>'Adrogué','state_id'=>1818 ],
        [ 'name'=>'Villa Espora','state_id'=>1818 ],
        [ 'name'=>'Villa Nueva','state_id'=>1818 ],
        [ 'name'=>'Luis Guillón','state_id'=>1818 ],
        [ 'name'=>'Monte Grande','state_id'=>1818 ],
        [ 'name'=>'9 de Abril','state_id'=>1818 ],
        [ 'name'=>'Morón','state_id'=>1818 ],
        [ 'name'=>'Parada Robles','state_id'=>1818 ],
        [ 'name'=>'Pavón','state_id'=>1818 ],
        [ 'name'=>'Aeropuerto Internacional Ezeiza','state_id'=>1818 ],
        [ 'name'=>'Canning','state_id'=>1818 ],
        [ 'name'=>'Carlos Spegazzini','state_id'=>1818 ],
        [ 'name'=>'José María Ezeiza','state_id'=>1818 ],
        [ 'name'=>'La Unión','state_id'=>1818 ],
        [ 'name'=>'Tristán Suárez','state_id'=>1818 ],
        [ 'name'=>'Bosques','state_id'=>1818 ],
        [ 'name'=>'Estanislao Severo Zeballos','state_id'=>1818 ],
        [ 'name'=>'San Juan Bautista','state_id'=>1818 ],
        [ 'name'=>'Gobernador Julio A. Costa','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Juan Allan','state_id'=>1818 ],
        [ 'name'=>'Villa Brown','state_id'=>1818 ],
        [ 'name'=>'Villa San Luis','state_id'=>1818 ],
        [ 'name'=>'Villa Santa Rosa','state_id'=>1818 ],
        [ 'name'=>'Villa Vatteone','state_id'=>1818 ],
        [ 'name'=>'El Tropezón','state_id'=>1818 ],
        [ 'name'=>'La Capilla','state_id'=>1818 ],
        [ 'name'=>'José C. Paz','state_id'=>1818 ],
        [ 'name'=>'Barrio Kennedy','state_id'=>1818 ],
        [ 'name'=>'General Juan Madariaga','state_id'=>1818 ],
        [ 'name'=>'Camet','state_id'=>1818 ],
        [ 'name'=>'Estación Camet','state_id'=>1818 ],
        [ 'name'=>'Mar del Plata','state_id'=>1818 ],
        [ 'name'=>'Punta Mogotes','state_id'=>1818 ],
        [ 'name'=>'Barrio El Casal','state_id'=>1818 ],
        [ 'name'=>'Barrio Colinas Verdes','state_id'=>1818 ],
        [ 'name'=>'Barrio El Coyunco','state_id'=>1818 ],
        [ 'name'=>'Barrio Gambier','state_id'=>1818 ],
        [ 'name'=>'Barrio La Gloria','state_id'=>1818 ],
        [ 'name'=>'Sierra de los Padres','state_id'=>1818 ],
        [ 'name'=>'Barrio Morabo','state_id'=>1818 ],
        [ 'name'=>'Barrio Ruta 24 Kilómetro 10','state_id'=>1818 ],
        [ 'name'=>'Country Club Bosque Real','state_id'=>1818 ],
        [ 'name'=>'General Rodríguez','state_id'=>1818 ],
        [ 'name'=>'Villa Yapeyú','state_id'=>1818 ],
        [ 'name'=>'Barrio Parque General San Martín','state_id'=>1818 ],
        [ 'name'=>'El Remanso','state_id'=>1818 ],
        [ 'name'=>'Billinghurst','state_id'=>1818 ],
        [ 'name'=>'Ciudad del Libertador General San Martín','state_id'=>1818 ],
        [ 'name'=>'Ciudad Jardín El Libertador','state_id'=>1818 ],
        [ 'name'=>'Villa Ayacucho','state_id'=>1818 ],
        [ 'name'=>'Villa Ballester','state_id'=>1818 ],
        [ 'name'=>'Villa Bernardo Monteagudo','state_id'=>1818 ],
        [ 'name'=>'Del Viso','state_id'=>1818 ],
        [ 'name'=>'Tortuguitas','state_id'=>1818 ],
        [ 'name'=>'Villa Chacabuco','state_id'=>1818 ],
        [ 'name'=>'Villa Coronel José M. Zapiola','state_id'=>1818 ],
        [ 'name'=>'Villa General Antonio J. de Sucre','state_id'=>1818 ],
        [ 'name'=>'Villa General Eugenio Necochea','state_id'=>1818 ],
        [ 'name'=>'Villa General José Tomás Guido','state_id'=>1818 ],
        [ 'name'=>'Villa General Juan G. Las Heras','state_id'=>1818 ],
        [ 'name'=>'Villa Godoy Cruz','state_id'=>1818 ],
        [ 'name'=>'Villa Granaderos de San Martín','state_id'=>1818 ],
        [ 'name'=>'Villa Gregoria Matorras','state_id'=>1818 ],
        [ 'name'=>'Villa José León Suárez','state_id'=>1818 ],
        [ 'name'=>'Villa Juan Martín de Pueyrredón','state_id'=>1818 ],
        [ 'name'=>'Villa Libertad','state_id'=>1818 ],
        [ 'name'=>'Villa Lynch','state_id'=>1818 ],
        [ 'name'=>'Villa Maipú','state_id'=>1818 ],
        [ 'name'=>'Va.María Irene de los Remedios Escalada','state_id'=>1818 ],
        [ 'name'=>'Va.Marqués Alejandro María de Aguado','state_id'=>1818 ],
        [ 'name'=>'Villa Parque Presidente Figueroa Alcorta','state_id'=>1818 ],
        [ 'name'=>'Villa Parque San Lorenzo','state_id'=>1818 ],
        [ 'name'=>'Villa San Andrés','state_id'=>1818 ],
        [ 'name'=>'Hurlingham','state_id'=>1818 ],
        [ 'name'=>'Villa Santos Tesei','state_id'=>1818 ],
        [ 'name'=>'William C. Morris','state_id'=>1818 ],
        [ 'name'=>'Ituzaingó Centro','state_id'=>1818 ],
        [ 'name'=>'Ituzaingó Sur','state_id'=>1818 ],
        [ 'name'=>'Mar del Tuyú','state_id'=>1818 ],
        [ 'name'=>'Santa Teresita','state_id'=>1818 ],
        [ 'name'=>'Aldo Bonzi','state_id'=>1818 ],
        [ 'name'=>'Ciudad Evita','state_id'=>1818 ],
        [ 'name'=>'González Catán','state_id'=>1818 ],
        [ 'name'=>'Gregorio de Laferrere','state_id'=>1818 ],
        [ 'name'=>'Isidro Casanova','state_id'=>1818 ],
        [ 'name'=>'La Tablada','state_id'=>1818 ],
        [ 'name'=>'Lomas del Mirador','state_id'=>1818 ],
        [ 'name'=>'Rafael Castillo','state_id'=>1818 ],
        [ 'name'=>'Ramos Mejía','state_id'=>1818 ],
        [ 'name'=>'San Justo','state_id'=>1818 ],
        [ 'name'=>'Tapiales','state_id'=>1818 ],
        [ 'name'=>'20 de Junio','state_id'=>1818 ],
        [ 'name'=>'Villa Eduardo Madero','state_id'=>1818 ],
        [ 'name'=>'Villa Luzuriaga','state_id'=>1818 ],
        [ 'name'=>'Villa Gobernador Udadondo','state_id'=>1818 ],
        [ 'name'=>'Virrey del Pino','state_id'=>1818 ],
        [ 'name'=>'Gerli','state_id'=>1818 ],
        [ 'name'=>'Lanús Este','state_id'=>1818 ],
        [ 'name'=>'Lanús Oeste','state_id'=>1818 ],
        [ 'name'=>'Monte Chingolo','state_id'=>1818 ],
        [ 'name'=>'Remedios de Escalada de San Martín','state_id'=>1818 ],
        [ 'name'=>'Valentín Alsina','state_id'=>1818 ],
        [ 'name'=>'Ángel Etcheverry','state_id'=>1818 ],
        [ 'name'=>'Arana','state_id'=>1818 ],
        [ 'name'=>'Arturo Seguí','state_id'=>1818 ],
        [ 'name'=>'Barrio El Carmen Oeste','state_id'=>1818 ],
        [ 'name'=>'Barrio Las Malvinas','state_id'=>1818 ],
        [ 'name'=>'Barrio Las Quintas','state_id'=>1818 ],
        [ 'name'=>'El Retiro','state_id'=>1818 ],
        [ 'name'=>'Joaquín Gorina','state_id'=>1818 ],
        [ 'name'=>'José Hernández','state_id'=>1818 ],
        [ 'name'=>'José Melchor Romero','state_id'=>1818 ],
        [ 'name'=>'La Cumbre','state_id'=>1818 ],
        [ 'name'=>'La Plata','state_id'=>1818 ],
        [ 'name'=>'Lisandro Olmos','state_id'=>1818 ],
        [ 'name'=>'Los Hornos','state_id'=>1818 ],
        [ 'name'=>'Manuel B. Gonnet','state_id'=>1818 ],
        [ 'name'=>'Ringuelet','state_id'=>1818 ],
        [ 'name'=>'Rufino de Elizalde','state_id'=>1818 ],
        [ 'name'=>'Tolosa','state_id'=>1818 ],
        [ 'name'=>'Transradio','state_id'=>1818 ],
        [ 'name'=>'Villa Elisa','state_id'=>1818 ],
        [ 'name'=>'Villa Elvira','state_id'=>1818 ],
        [ 'name'=>'Villa Garibaldi','state_id'=>1818 ],
        [ 'name'=>'Villa Montoro','state_id'=>1818 ],
        [ 'name'=>'Villa Parque Sicardi','state_id'=>1818 ],
        [ 'name'=>'Banfield','state_id'=>1818 ],
        [ 'name'=>'Llavallol','state_id'=>1818 ],
        [ 'name'=>'Lomas de Zamora','state_id'=>1818 ],
        [ 'name'=>'Temperley','state_id'=>1818 ],
        [ 'name'=>'Turdera','state_id'=>1818 ],
        [ 'name'=>'Villa Centenario','state_id'=>1818 ],
        [ 'name'=>'Villa Fiorito','state_id'=>1818 ],
        [ 'name'=>'Barrio Las Casuarinas','state_id'=>1818 ],
        [ 'name'=>'Cortines','state_id'=>1818 ],
        [ 'name'=>'Lezica y Torrezuri','state_id'=>1818 ],
        [ 'name'=>'Luján','state_id'=>1818 ],
        [ 'name'=>'Villa Flandria Norte','state_id'=>1818 ],
        [ 'name'=>'Villa Flandria Sur','state_id'=>1818 ],
        [ 'name'=>'Country Club Las Praderas','state_id'=>1818 ],
        [ 'name'=>'Open Door','state_id'=>1818 ],
        [ 'name'=>'Área de Promoción El Triángulo','state_id'=>1818 ],
        [ 'name'=>'Grand Bourg','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Adolfo Sourdeaux','state_id'=>1818 ],
        [ 'name'=>'Ingeniero Pablo Nogués','state_id'=>1818 ],
        [ 'name'=>'Los Polvorines','state_id'=>1818 ],
        [ 'name'=>'Abasto','state_id'=>1818 ],
        [ 'name'=>'City Bell','state_id'=>1818 ],
        [ 'name'=>'Malvinas Argentinas','state_id'=>1818 ],
        [ 'name'=>'Tortuguitas','state_id'=>1818 ],
        [ 'name'=>'Villa de Mayo','state_id'=>1818 ],
        [ 'name'=>'La Baliza','state_id'=>1818 ],
        [ 'name'=>'La Caleta','state_id'=>1818 ],
        [ 'name'=>'Mar de Cobo','state_id'=>1818 ],
        [ 'name'=>'Atlántida','state_id'=>1818 ],
        [ 'name'=>'Camet Norte','state_id'=>1818 ],
        [ 'name'=>'Frente Mar','state_id'=>1818 ],
        [ 'name'=>'Playa Dorada','state_id'=>1818 ],
        [ 'name'=>'Santa Clara del Mar','state_id'=>1818 ],
        [ 'name'=>'Santa Elena','state_id'=>1818 ],
        [ 'name'=>'Barrio Lisandro de la Torre y Santa Marta','state_id'=>1818 ],
        [ 'name'=>'Marcos Paz','state_id'=>1818 ],
        [ 'name'=>'Libertad','state_id'=>1818 ],
        [ 'name'=>'Mariano Acosta','state_id'=>1818 ],
        [ 'name'=>'Pontevedra','state_id'=>1818 ],
        [ 'name'=>'San Antonio de Padua','state_id'=>1818 ],
        [ 'name'=>'Cuartel V','state_id'=>1818 ],
        [ 'name'=>'Francisco Álvarez','state_id'=>1818 ],
        [ 'name'=>'La Reja','state_id'=>1818 ],
        [ 'name'=>'Moreno','state_id'=>1818 ],
        [ 'name'=>'Paso del Rey','state_id'=>1818 ],
        [ 'name'=>'Castelar','state_id'=>1818 ],
        [ 'name'=>'El Palomar','state_id'=>1818 ],
        [ 'name'=>'Haedo','state_id'=>1818 ],
        [ 'name'=>'Villa Sarmiento','state_id'=>1818 ],
        [ 'name'=>'Necochea','state_id'=>1818 ],
        [ 'name'=>'Quequén','state_id'=>1818 ],
        [ 'name'=>'Costa Bonita','state_id'=>1818 ],
        [ 'name'=>'Colonia Hinojo','state_id'=>1818 ],
        [ 'name'=>'Hinojo','state_id'=>1818 ],
        [ 'name'=>'Sierras Bayas','state_id'=>1818 ],
        [ 'name'=>'Villa Arrieta','state_id'=>1818 ],
        [ 'name'=>'Del Viso','state_id'=>1818 ],
        [ 'name'=>'Fátima','state_id'=>1818 ],
        [ 'name'=>'La Lonja','state_id'=>1818 ],
        [ 'name'=>'Los Cachorros','state_id'=>1818 ],
        [ 'name'=>'Manzanares','state_id'=>1818 ],
        [ 'name'=>'Manzone','state_id'=>1818 ],
        [ 'name'=>'Maquinista F. Savio Oeste','state_id'=>1818 ],
        [ 'name'=>'Pilar','state_id'=>1818 ],
        [ 'name'=>'Presidente Derqui','state_id'=>1818 ],
        [ 'name'=>'Roberto de Vicenzo','state_id'=>1818 ],
        [ 'name'=>'Santa Teresa','state_id'=>1818 ],
        [ 'name'=>'Tortuguitas','state_id'=>1818 ],
        [ 'name'=>'Villa Astolfi','state_id'=>1818 ],
        [ 'name'=>'Villa Rosa','state_id'=>1818 ],
        [ 'name'=>'Zelaya','state_id'=>1818 ],
        [ 'name'=>'Trujui','state_id'=>1818 ],
        [ 'name'=>'Cariló','state_id'=>1818 ],
        [ 'name'=>'Ostende','state_id'=>1818 ],
        [ 'name'=>'Pinamar','state_id'=>1818 ],
        [ 'name'=>'Valeria del Mar','state_id'=>1818 ],
        [ 'name'=>'Barrio América Unida','state_id'=>1818 ],
        [ 'name'=>'Guernica','state_id'=>1818 ],
        [ 'name'=>'Bernal','state_id'=>1818 ],
        [ 'name'=>'Bernal Oeste','state_id'=>1818 ],
        [ 'name'=>'Don Bosco','state_id'=>1818 ],
        [ 'name'=>'Ezpeleta','state_id'=>1818 ],
        [ 'name'=>'Ezpeleta Oeste','state_id'=>1818 ],
        [ 'name'=>'Quilmes','state_id'=>1818 ],
        [ 'name'=>'Quilmes Oeste','state_id'=>1818 ],
        [ 'name'=>'San Francisco Solano','state_id'=>1818 ],
        [ 'name'=>'Villa La Florida','state_id'=>1818 ],
        [ 'name'=>'Barrio Las Margaritas','state_id'=>1818 ],
        [ 'name'=>'Rojas','state_id'=>1818 ],
        [ 'name'=>'Villa Parque Cecir','state_id'=>1818 ],
        [ 'name'=>'San Fernando','state_id'=>1818 ],
        [ 'name'=>'Victoria','state_id'=>1818 ],
        [ 'name'=>'Virreyes','state_id'=>1818 ],
        [ 'name'=>'Acasusso','state_id'=>1818 ],
        [ 'name'=>'Béccar','state_id'=>1818 ],
        [ 'name'=>'Boulogne Sur Mer','state_id'=>1818 ],
        [ 'name'=>'Martínez','state_id'=>1818 ],
        [ 'name'=>'San Isidro','state_id'=>1818 ],
        [ 'name'=>'Villa Adelina','state_id'=>1818 ],
        [ 'name'=>'Bella Vista','state_id'=>1818 ],
        [ 'name'=>'Campo de Mayo','state_id'=>1818 ],
        [ 'name'=>'Muñiz','state_id'=>1818 ],
        [ 'name'=>'San Miguel','state_id'=>1818 ],
        [ 'name'=>'Campos Salles','state_id'=>1818 ],
        [ 'name'=>'San Nicolás de los Arroyos','state_id'=>1818 ],
        [ 'name'=>'Alejandro Korn','state_id'=>1818 ],
        [ 'name'=>'San Vicente','state_id'=>1818 ],
        [ 'name'=>'Domselaar','state_id'=>1818 ],
        [ 'name'=>'Benavídez','state_id'=>1818 ],
        [ 'name'=>'Dique Luján','state_id'=>1818 ],
        [ 'name'=>'Don Torcuato Este','state_id'=>1818 ],
        [ 'name'=>'Don Torcuato Oeste','state_id'=>1818 ],
        [ 'name'=>'El Talar','state_id'=>1818 ],
        [ 'name'=>'General Pacheco','state_id'=>1818 ],
        [ 'name'=>'Troncos del Talar','state_id'=>1818 ],
        [ 'name'=>'Ricardo Rojas','state_id'=>1818 ],
        [ 'name'=>'Rincón de Milberg','state_id'=>1818 ],
        [ 'name'=>'Tigre','state_id'=>1818 ],
        [ 'name'=>'Claromecó','state_id'=>1818 ],
        [ 'name'=>'Dunamar','state_id'=>1818 ],
        [ 'name'=>'Caseros','state_id'=>1818 ],
        [ 'name'=>'Churruca','state_id'=>1818 ],
        [ 'name'=>'Ciudad Jardín Lomas del Palomar','state_id'=>1818 ],
        [ 'name'=>'Ciudadela','state_id'=>1818 ],
        [ 'name'=>'El Libertador','state_id'=>1818 ],
        [ 'name'=>'José Ingenieros','state_id'=>1818 ],
        [ 'name'=>'Loma Hermosa','state_id'=>1818 ],
        [ 'name'=>'Martín Coronado','state_id'=>1818 ],
        [ 'name'=>'11 de Septiembre','state_id'=>1818 ],
        [ 'name'=>'Pablo Podestá','state_id'=>1818 ],
        [ 'name'=>'Remedios de Escalada','state_id'=>1818 ],
        [ 'name'=>'Sáenz Peña','state_id'=>1818 ],
        [ 'name'=>'Santos Lugares','state_id'=>1818 ],
        [ 'name'=>'Villa Bosch','state_id'=>1818 ],
        [ 'name'=>'Villa Raffo','state_id'=>1818 ],
        [ 'name'=>'Carapachay','state_id'=>1818 ],
        [ 'name'=>'Florida','state_id'=>1818 ],
        [ 'name'=>'Florida Oeste','state_id'=>1818 ],
        [ 'name'=>'La Lucila','state_id'=>1818 ],
        [ 'name'=>'Munro','state_id'=>1818 ],
        [ 'name'=>'Olivos','state_id'=>1818 ],
        [ 'name'=>'Vicente López','state_id'=>1818 ],
        [ 'name'=>'Villa Adelina','state_id'=>1818 ],
        [ 'name'=>'Villa Martelli','state_id'=>1818 ],
        [ 'name'=>'Barrio Saavedra','state_id'=>1818 ],
        [ 'name'=>'Zárate','state_id'=>1818 ]
    ];
    Locations::insert($data);
}

}