<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Locations;

class LocalidadesCatamarcaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->createLocalidades();
    }

    private function createLocalidades(){
        $data = [
            ['name'=>'Andalhualá', 'state_id'=>1819],
            ['name'=>'Chañar Punco', 'state_id'=>1819],
            ['name'=>'El Desmonte', 'state_id'=>1819],
            ['name'=>'El Puesto', 'state_id'=>1819],
            ['name'=>'Famatanca', 'state_id'=>1819],
            ['name'=>'Las Mojarras', 'state_id'=>1819],
            ['name'=>'Punta de Balasto', 'state_id'=>1819],
            ['name'=>'San José', 'state_id'=>1819],
            ['name'=>'Santa María', 'state_id'=>1819],
            ['name'=>'Yapes', 'state_id'=>1819],
            ['name'=>'Bañado de Ovanta', 'state_id'=>1819],
            ['name'=>'Las Cañas', 'state_id'=>1819],
            ['name'=>'Lavalle', 'state_id'=>1819],
            ['name'=>'San Pedro', 'state_id'=>1819],
            ['name'=>'El Cajón', 'state_id'=>1819],
            ['name'=>'Fuerte Quemado', 'state_id'=>1819],
            ['name'=>'La Hoyada', 'state_id'=>1819],
            ['name'=>'Antofagasta de la Sierra', 'state_id'=>1819],
            ['name'=>'El Peñón', 'state_id'=>1819],
            ['name'=>'Los Nacimientos', 'state_id'=>1819],
            ['name'=>'Chuchucaruana', 'state_id'=>1819],
            ['name'=>'Colpes', 'state_id'=>1819],
            ['name'=>'El Bolsón', 'state_id'=>1819],
            ['name'=>'El Rodeo', 'state_id'=>1819],
            ['name'=>'Huaycama', 'state_id'=>1819],
            ['name'=>'La Puerta', 'state_id'=>1819],
            ['name'=>'Las Chacritas', 'state_id'=>1819],
            ['name'=>'Las Juntas', 'state_id'=>1819],
            ['name'=>'Los Castillos', 'state_id'=>1819],
            ['name'=>'Los Talas', 'state_id'=>1819],
            ['name'=>'Los Varela', 'state_id'=>1819],
            ['name'=>'Singuil', 'state_id'=>1819],
            ['name'=>'El Alamito', 'state_id'=>1819],
            ['name'=>'El Lindero', 'state_id'=>1819],
            ['name'=>'Amadores', 'state_id'=>1819],
            ['name'=>'La Higuera', 'state_id'=>1819],
            ['name'=>'La Merced', 'state_id'=>1819],
            ['name'=>'La Viña', 'state_id'=>1819],
            ['name'=>'Las Lajas', 'state_id'=>1819],
            ['name'=>'Monte Potrero', 'state_id'=>1819],
            ['name'=>'San Antonio', 'state_id'=>1819],
            ['name'=>'Villa de Balcozna', 'state_id'=>1819],
            ['name'=>'Alijilán', 'state_id'=>1819],
            ['name'=>'Los Altos', 'state_id'=>1819],
            ['name'=>'Manantiales', 'state_id'=>1819],
            ['name'=>'Andalgalá', 'state_id'=>1819],
            ['name'=>'Chaquiago', 'state_id'=>1819],
            ['name'=>'Choya', 'state_id'=>1819],
            ['name'=>'El Potrero', 'state_id'=>1819],
            ['name'=>'Colpes', 'state_id'=>1819],
            ['name'=>'Rincón', 'state_id'=>1819],
            ['name'=>'San Miguel', 'state_id'=>1819],
            ['name'=>'Saujil', 'state_id'=>1819],
            ['name'=>'Siján', 'state_id'=>1819],
            ['name'=>'Ancasti', 'state_id'=>1819],
            ['name'=>'Anquincila', 'state_id'=>1819],
            ['name'=>'La Candelaria', 'state_id'=>1819],
            ['name'=>'La Majada', 'state_id'=>1819],
            ['name'=>'Capayán', 'state_id'=>1819],
            ['name'=>'Chumbicha', 'state_id'=>1819],
            ['name'=>'Colonia del Valle', 'state_id'=>1819],
            ['name'=>'Colonia Nueva Coneta', 'state_id'=>1819],
            ['name'=>'Concepción', 'state_id'=>1819],
            ['name'=>'Coneta', 'state_id'=>1819],
            ['name'=>'El Bañado', 'state_id'=>1819],
            ['name'=>'Huillapima', 'state_id'=>1819],
            ['name'=>'Los Angeles', 'state_id'=>1819],
            ['name'=>'Miraflores', 'state_id'=>1819],
            ['name'=>'San Pablo', 'state_id'=>1819],
            ['name'=>'San Pedro', 'state_id'=>1819],
            ['name'=>'San Fernando del Valle de Catamarca', 'state_id'=>1819],
            ['name'=>'El Alto', 'state_id'=>1819],
            ['name'=>'Guayamba', 'state_id'=>1819],
            ['name'=>'Infanzón', 'state_id'=>1819],
            ['name'=>'Los Corrales', 'state_id'=>1819],
            ['name'=>'Tapso', 'state_id'=>1819],
            ['name'=>'Vilismán', 'state_id'=>1819],
            ['name'=>'Pomancillo Este', 'state_id'=>1819],
            ['name'=>'Pomancillo Oeste', 'state_id'=>1819],
            ['name'=>'San José', 'state_id'=>1819],
            ['name'=>'Villa Las Pirquitas', 'state_id'=>1819],
            ['name'=>'El Aybal', 'state_id'=>1819],
            ['name'=>'Icaño', 'state_id'=>1819],
            ['name'=>'Las Esquinas', 'state_id'=>1819],
            ['name'=>'Las Palmitas', 'state_id'=>1819],
            ['name'=>'Quirós', 'state_id'=>1819],
            ['name'=>'Ramblones', 'state_id'=>1819],
            ['name'=>'San Antonio', 'state_id'=>1819],
            ['name'=>'Palo Labrado', 'state_id'=>1819],
            ['name'=>'Colana', 'state_id'=>1819],
            ['name'=>'El Pajonal', 'state_id'=>1819],
            ['name'=>'Mutquin', 'state_id'=>1819],
            ['name'=>'Pomán', 'state_id'=>1819],
            ['name'=>'El Portezuelo', 'state_id'=>1819],
            ['name'=>'Huaycama', 'state_id'=>1819],
            ['name'=>'Las Tejas', 'state_id'=>1819],
            ['name'=>'San Isidro', 'state_id'=>1819],
            ['name'=>'Santa Cruz', 'state_id'=>1819],
            ['name'=>'San Martín', 'state_id'=>1819],
            ['name'=>'Casa de Piedra', 'state_id'=>1819],
            ['name'=>'El Bañado', 'state_id'=>1819],
            ['name'=>'El Divisadero', 'state_id'=>1819],
            ['name'=>'El Quimilo', 'state_id'=>1819],
            ['name'=>'Esquiú', 'state_id'=>1819],
            ['name'=>'La Dorada', 'state_id'=>1819],
            ['name'=>'La Guardia', 'state_id'=>1819],
            ['name'=>'Recreo', 'state_id'=>1819],
            ['name'=>'El Salado', 'state_id'=>1819],
            ['name'=>'Amanao', 'state_id'=>1819],
            ['name'=>'Barranca Larga', 'state_id'=>1819],
            ['name'=>'Belén', 'state_id'=>1819],
            ['name'=>'Cóndor Huasi', 'state_id'=>1819],
            ['name'=>'Corral Quemado', 'state_id'=>1819],
            ['name'=>'El Durazno', 'state_id'=>1819],
            ['name'=>'Farallón Negro', 'state_id'=>1819],
            ['name'=>'Hualfín', 'state_id'=>1819],
            ['name'=>'Jacipunco', 'state_id'=>1819],
            ['name'=>'La Puntilla', 'state_id'=>1819],
            ['name'=>'Las Juntas', 'state_id'=>1819],
            ['name'=>'Londres', 'state_id'=>1819],
            ['name'=>'Los Nacimientos', 'state_id'=>1819],
            ['name'=>'Puerta de Corral Quemado', 'state_id'=>1819],
            ['name'=>'Puerta de San José', 'state_id'=>1819],
            ['name'=>'Villa Vil', 'state_id'=>1819],
            ['name'=>'Anillaco', 'state_id'=>1819],
            ['name'=>'Copacabana', 'state_id'=>1819],
            ['name'=>'El Puesto', 'state_id'=>1819],
            ['name'=>'Fiambalá', 'state_id'=>1819],
            ['name'=>'Medanitos', 'state_id'=>1819],
            ['name'=>'Palo Blanco', 'state_id'=>1819],
            ['name'=>'Saujil', 'state_id'=>1819],
            ['name'=>'Tinogasta', 'state_id'=>1819],
            ['name'=>'Buena Vista', 'state_id'=>1819],
            ['name'=>'El Alamito', 'state_id'=>1819],
            ['name'=>'Aconquija', 'state_id'=>1819],
            ['name'=>'Alto de las Juntas', 'state_id'=>1819],
            ['name'=>'El Lindero', 'state_id'=>1819],
            ['name'=>'La Mesada', 'state_id'=>1819],
            ['name'=>'Los Ángeles Norte', 'state_id'=>1819],
            ['name'=>'Los Ángeles Sur', 'state_id'=>1819],
            ['name'=>'El Hueco', 'state_id'=>1819],
            ['name'=>'La Carrera', 'state_id'=>1819],
            ['name'=>'La Falda de San Antonio', 'state_id'=>1819],
            ['name'=>'La Tercena', 'state_id'=>1819],
            ['name'=>'San Antonio', 'state_id'=>1819],
            ['name'=>'San José', 'state_id'=>1819],
            ['name'=>'Chañar Punco', 'state_id'=>1819],
            ['name'=>'Lampacito', 'state_id'=>1819],
            ['name'=>'Medanitos', 'state_id'=>1819],
            ['name'=>'Famatanca', 'state_id'=>1819],
            ['name'=>'San José Banda', 'state_id'=>1819],
            ['name'=>'El Cerrito', 'state_id'=>1819],
            ['name'=>'Las Mojarras', 'state_id'=>1819],
            ['name'=>'Casa de Piedra', 'state_id'=>1819],
            ['name'=>'La Puntilla', 'state_id'=>1819],
            ['name'=>'Palo Seco', 'state_id'=>1819],
            ['name'=>'San José Norte', 'state_id'=>1819],
            ['name'=>'San José Villa', 'state_id'=>1819],
            ['name'=>'Copacabana', 'state_id'=>1819],
            ['name'=>'La Puntilla', 'state_id'=>1819],
            ['name'=>'Fiambalá', 'state_id'=>1819],
            ['name'=>'La Ramadita', 'state_id'=>1819],
            ['name'=>'Pampa Blanca', 'state_id'=>1819],
            ['name'=>'El Bañado', 'state_id'=>1819],
            ['name'=>'Polcos', 'state_id'=>1819],
            ['name'=>'Pozo del Mistol', 'state_id'=>1819],
            ['name'=>'San Isidro', 'state_id'=>1819],
            ['name'=>'Santa Rosa', 'state_id'=>1819],
            ['name'=>'Sumalao', 'state_id'=>1819],
            ['name'=>'Villa Dolores', 'state_id'=>1819]

        ];

        Locations::insert($data);
    }
}
