<?php

namespace Database\Seeders;

use App\Models\States;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $this->createStates();
    }

    private function createStates(){
        $data = [
            ['id'=>1596,    'country_id'=>	89,'name'=>	'Amazonas'],
            ['id'=>1597,    'country_id'=>	89,'name'=>	'Ancash'],
            ['id'=>1598,    'country_id'=>	89,'name'=>	'Apurímac'],
            ['id'=>1599,    'country_id'=>	89,'name'=>	'Arequipa'],
            ['id'=>1600,    'country_id'=>	89,'name'=>	'Ayacucho'],
            ['id'=>1601,    'country_id'=>	89,'name'=>	'Cajamarca'],
            ['id'=>1602,    'country_id'=>	89,'name'=>	'Callao'],
            ['id'=>1603,    'country_id'=>	89,'name'=>	'Cusco'],
            ['id'=>1604,    'country_id'=>	89,'name'=>	'Huancavelica'],
            ['id'=>1605,    'country_id'=>	89,'name'=>	'Huánuco'],
            ['id'=>1606,    'country_id'=>	89,'name'=>	'Ica'],
            ['id'=>1607,    'country_id'=>	89,'name'=>	'Junín'],
            ['id'=>1608,    'country_id'=>	89,'name'=>	'La Libertad'],
            ['id'=>1609,    'country_id'=>	89,'name'=>	'Lambayeque'],
            ['id'=>1610,    'country_id'=>	89,'name'=>	'Lima'],
            ['id'=>1611,    'country_id'=>	89,'name'=>	'Loreto'],
            ['id'=>1612,    'country_id'=>	89,'name'=>	'Madre de Dios'],
            ['id'=>1613,    'country_id'=>	89,'name'=>	'Moquegua'],
            ['id'=>1614,    'country_id'=>	89,'name'=>	'Pasco'],
            ['id'=>1615,    'country_id'=>	89,'name'=>	'Piura'],
            ['id'=>1616,    'country_id'=>	89,'name'=>	'Puno'],
            ['id'=>1617,    'country_id'=>	89,'name'=>	'San Martín'],
            ['id'=>1618,    'country_id'=>	89,'name'=>	'Tacna'],
            ['id'=>1619,    'country_id'=>	89,'name'=>	'Tumbes'],
            ['id'=>1620,    'country_id'=>	89,'name'=>	'Ucayali'],
            ['id'=>1622,    'country_id'=>	110,'name'=>	'Alto Paraná'],
            ['id'=>1623,    'country_id'=>	110,'name'=>	'Amambay'],
            ['id'=>1624,    'country_id'=>	110,'name'=>	'Boquerón'],
            ['id'=>1625,    'country_id'=>	110,'name'=>	'Caaguaz&uacute;'],
            ['id'=>1626,    'country_id'=>	110,'name'=>	'Caazapá'],
            ['id'=>1627,    'country_id'=>	110,'name'=>	'Central'],
            ['id'=>1628,    'country_id'=>	110,'name'=>	'Concepción'],
            ['id'=>1629,    'country_id'=>	110,'name'=>	'Cordillera'],
            ['id'=>1630,    'country_id'=>	110,'name'=>	'Guairá'],
            ['id'=>1631,    'country_id'=>	110,'name'=>	'Itap&uacute;a'],
            ['id'=>1632,    'country_id'=>	110,'name'=>	'Misiones'],
            ['id'=>1633,    'country_id'=>	110,'name'=>	'Neembuc&uacute;'],
            ['id'=>1634,    'country_id'=>	110,'name'=>	'Paraguarí'],
            ['id'=>1635,    'country_id'=>	110,'name'=>	'Presidente Hayes'],
            ['id'=>1636,    'country_id'=>	110,'name'=>	'San Pedro'],
            ['id'=>1637,    'country_id'=>	110,'name'=>	'Alto Paraguay'],
            ['id'=>1638,    'country_id'=>	110,'name'=>	'Canindey&uacute;'],
            ['id'=>1639,    'country_id'=>	110,'name'=>	'Chaco'],
            ['id'=>1642,    'country_id'=>	111,'name'=>	'Artigas'],
            ['id'=>1643,    'country_id'=>	111,'name'=>	'Canelones'],
            ['id'=>1644,    'country_id'=>	111,'name'=>	'Cerro Largo'],
            ['id'=>1645,    'country_id'=>	111,'name'=>	'Colonia'],
            ['id'=>1646,    'country_id'=>	111,'name'=>	'Durazno'],
            ['id'=>1647,    'country_id'=>	111,'name'=>	'Flores'],
            ['id'=>1648,    'country_id'=>	111,'name'=>	'Florida'],
            ['id'=>1649,    'country_id'=>	111,'name'=>	'Lavalleja'],
            ['id'=>1650,    'country_id'=>	111,'name'=>	'Maldonado'],
            ['id'=>1651,    'country_id'=>	111,'name'=>	'Montevideo'],
            ['id'=>1652,    'country_id'=>	111,'name'=>	'Paysand&uacute;'],
            ['id'=>1653,    'country_id'=>	111,'name'=>	'Río Negro'],
            ['id'=>1654,    'country_id'=>	111,'name'=>	'Rivera'],
            ['id'=>1655,    'country_id'=>	111,'name'=>	'Rocha'],
            ['id'=>1656,    'country_id'=>	111,'name'=>	'Salto'],
            ['id'=>1657,    'country_id'=>	111,'name'=>	'San José'],
            ['id'=>1658,    'country_id'=>	111,'name'=>	'Soriano'],
            ['id'=>1659,    'country_id'=>	111,'name'=>	'Tacuarembó'],
            ['id'=>1660,    'country_id'=>	111,'name'=>	'Treinta y Tres'],
            ['id'=>1662,    'country_id'=>	81,'name'=> 	'Región de Tarapacá'],
            ['id'=>1663,    'country_id'=>	81,'name'=> 	'Región de Antofagasta'],
            ['id'=>1664,    'country_id'=>	81,'name'=> 	'Región de Atacama'],
            ['id'=>1665,    'country_id'=>	81,'name'=> 	'Región de Coquimbo'],
            ['id'=>1666,    'country_id'=>	81,'name'=> 	'Región de Valparaíso'],
            ['id'=>1667,    'country_id'=>	81,'name'=> 	"Región del Libertador General Bernardo O'Higgins"],
            ['id'=>1668,    'country_id'=>	81,'name'=> 	'Región del Maule'],
            ['id'=>1669,    'country_id'=>	81,'name'=> 	'Región del Bío Bío'],
            ['id'=>1670,    'country_id'=>	81,'name'=> 	'Región de La Araucanía'],
            ['id'=>1671,    'country_id'=>	81,'name'=> 	'Región de Los Lagos'],
            ['id'=>1672,    'country_id'=>	81,'name'=> 	'Región Aisén del General Carlos Ibáñez del Campo'],
            ['id'=>1673,    'country_id'=>	81,'name'=> 	'Región de Magallanes y de la Antártica Chilena'],
            ['id'=>1674,    'country_id'=>	81,'name'=> 	'Región Metropolitana de Santiago'],
            ['id'=>1777,    'country_id'=>	123,'name'=>	'Chuquisaca'],
            ['id'=>1778,    'country_id'=>	123,'name'=>	'Cochabamba'],
            ['id'=>1779,    'country_id'=>	123,'name'=>	'El Beni'],
            ['id'=>1780,    'country_id'=>	123,'name'=>	'La Paz'],
            ['id'=>1781,    'country_id'=>	123,'name'=>	'Oruro'],
            ['id'=>1782,    'country_id'=>	123,'name'=>	'Pando'],
            ['id'=>1783,    'country_id'=>	123,'name'=>	'Potosí'],
            ['id'=>1784,    'country_id'=>	123,'name'=>	'Santa Cruz'],
            ['id'=>1785,    'country_id'=>	123,'name'=>	'Tarija'],
            ['id'=>1818,    'country_id'=>	5,'name'=>	'Buenos Aires'],
            ['id'=>1819,    'country_id'=>	5,'name'=>	'Catamarca'],
            ['id'=>1820,    'country_id'=>	5,'name'=>	'Chaco'],
            ['id'=>1821,    'country_id'=>	5,'name'=>	'Chubut'],
            ['id'=>1822,    'country_id'=>	5,'name'=>	'Córdoba'],
            ['id'=>1823,    'country_id'=>	5,'name'=>	'Corrientes'],
            ['id'=>1824,    'country_id'=>	5,'name'=>	'Distrito Federal'],
            ['id'=>1825,    'country_id'=>	5,'name'=>	'Entre Ríos'],
            ['id'=>1826,    'country_id'=>	5,'name'=>	'Formosa'],
            ['id'=>1827,    'country_id'=>	5,'name'=>	'Jujuy'],
            ['id'=>1828,    'country_id'=>	5,'name'=>	'La Pampa'],
            ['id'=>1829,    'country_id'=>	5,'name'=>	'La Rioja'],
            ['id'=>1830,    'country_id'=>	5,'name'=>	'Mendoza'],
            ['id'=>1831,    'country_id'=>	5,'name'=>	'Misiones'],
            ['id'=>1832,    'country_id'=>	5,'name'=>	'Neuquén'],
            ['id'=>1833,    'country_id'=>	5,'name'=>	'Río Negro'],
            ['id'=>1834,    'country_id'=>	5,'name'=>	'Salta'],
            ['id'=>1835,    'country_id'=>	5,'name'=>	'San Juan'],
            ['id'=>1836,    'country_id'=>	5,'name'=>	'San Luis'],
            ['id'=>1837,    'country_id'=>	5,'name'=>	'Santa Cruz'],
            ['id'=>1838,    'country_id'=>	5,'name'=>	'Santa Fe'],
            ['id'=>1839,    'country_id'=>	5,'name'=>	'Santiago del Estero'],
            ['id'=>1840,    'country_id'=>	5,'name'=>	'Tierra del Fuego'],
            ['id'=>1841,    'country_id'=>	5,'name'=>	'Tucumán'],
            ['id'=>1901,    'country_id'=>	12,'name'=>	'Acre'],
            ['id'=>1902,    'country_id'=>	12,'name'=>	'Alagoas'],
            ['id'=>1903,    'country_id'=>	12,'name'=>	'Amapa'],
            ['id'=>1904,    'country_id'=>	12,'name'=>	'Amazonas'],
            ['id'=>1905,    'country_id'=>	12,'name'=>	'Bahia'],
            ['id'=>1906,    'country_id'=>	12,'name'=>	'Ceara'],
            ['id'=>1907,    'country_id'=>	12,'name'=>	'Distrito Federal'],
            ['id'=>1908,    'country_id'=>	12,'name'=>	'Espirito Santo'],
            ['id'=>1909,    'country_id'=>	12,'name'=>	'Mato Grosso do Sul'],
            ['id'=>1910,    'country_id'=>	12,'name'=>	'Maranhao'],
            ['id'=>1911,    'country_id'=>	12,'name'=>	'Mato Grosso'],
            ['id'=>1912,    'country_id'=>	12,'name'=>	'Minas Gerais'],
            ['id'=>1913,    'country_id'=>	12,'name'=>	'Para'],
            ['id'=>1914,    'country_id'=>	12,'name'=>	'Paraiba'],
            ['id'=>1915,    'country_id'=>	12,'name'=>	'Parana'],
            ['id'=>1916,    'country_id'=>	12,'name'=>	'Piaui'],
            ['id'=>1917,    'country_id'=>	12,'name'=>	'Rio de Janeiro'],
            ['id'=>1918,    'country_id'=>	12,'name'=>	'Rio Grande do Norte'],
            ['id'=>1919,    'country_id'=>	12,'name'=>	'Rio Grande do Sul'],
            ['id'=>1920,    'country_id'=>	12,'name'=>	'Rondonia'],
            ['id'=>1921,    'country_id'=>	12,'name'=>	'Roraima'],
            ['id'=>1922,    'country_id'=>	12,'name'=>	'Santa Catarina'],
            ['id'=>1923,    'country_id'=>	12,'name'=>	'Sao Paulo'],
            ['id'=>1924,    'country_id'=>	12,'name'=>	'Sergipe'],
            ['id'=>1925,    'country_id'=>	12,'name'=>	'Goias'],
            ['id'=>1926,    'country_id'=>	12,'name'=>	'Pernambuco'],
            ['id'=>1927,    'country_id'=>	12,'name'=>	'Tocantins'],
            ['id'=>2202,    'country_id'=>	81,'name'=>	'Región de Los Ríos'],
            ['id'=>2203,    'country_id'=>	81,'name'=>	'Región de Arica y Parinacota']
        ];
        States::insert($data);
    }
}
